### PR TITLE
Add spring-security autoconfig for JSF resources.

### PR DESCRIPTION
**Pull request by nyilmaz**

### CODE REVIEW

**Comment by nyilmaz** [comment]
Since it's a ```static final``` field in ```ResourceHandler```, i think we can statically add such configuration:

https://javaserverfaces.java.net/docs/2.2/javadocs/constant-values.html#javax.faces.application.ResourceHandler.RESOURCE_IDENTIFIER

**Comment by persapiens** [comment]
Personally, I like this improvement, but do you think all application want to "unsecure" jsf resources?

If not, should we include one property "jsf.security.ignoreResources" to control this?

So, let's create specific autoconfiguration and properties classes for security?

I look forward your answer.

**Comment by persapiens** [comment]
Don't you think jsf resources should be ignored by default? This behaviour would emphasize this feature. In this case, jsf.security.ignoreResources value should be also considered "true" if no value is assigned.

Included tests are not mandatory, but would be a plus.

**Comment by nyilmaz** [comment]
Actually this feature is available indirectly through [`SecurityProperties`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/SecurityProperties.java#L93)

Better be documented (referenced) :)

**Pull request closed without merging**
