### PR TITLE
Upgrade to spring-boot 1.4

### PR DESCRIPTION
**Pull request by nyilmaz**
Upgraded spring-boot version to 1.4.0.RC2 and fixed jsp dependencies.

(modified .gitignore to ignore all target dirs and IDE conf files)

### CODE REVIEW

**Comment by persapiens** [comment]
Hello @nyilmaz,

Build is broken with spring-boot 1.4.0.RC1/RC2 because it is not available is Maven Central. At master branch, I prefer using final/stable instead of milestone/release candidate versions.

[spring-boot 1.4.0 final](https://github.com/spring-projects/spring-boot/milestone/42) is target to July 27. I think we could wait one week to merge your helpful pull request. What do you think?

**Comment by nyilmaz** [comment]
Oh sure, then we can consider this commit as a preliminary work for spring-boot 1.4.0. I tried running example modules, and did not face any complication btw.

**Comment by persapiens** [comment]
That's ok. As usual, thanks again for testing jetty compatibility @nyilmaz .

**Comment by persapiens** [comment]
@nyilmaz , spring 1.4.0.RELEASE has just been released. Could you rebase and push force on your existing branch with this version?

I look forward you answer.

**Comment by nyilmaz** [comment]
I'm on it, also want to check examples with this release.

**Comment by nyilmaz** [comment]
Tested all embedded containers with both myfaces and mojarra providers.

**Comment by persapiens** [comment]
Very good. 
I think this request is complete. 
I'll check @SprinbBootTest news before releasing.

**Pull request merged**
