### PR TITLE
upgrade mojarra to 2.3.3.99

### PR DESCRIPTION
**Pull request by persapiens**

### CODE REVIEW

**Comment by larsgrefer** [comment]
What a strange version number.

**Comment by larsgrefer** [comment]
In the `MOJARRA_2_3X_ROLLING` branch of the mojarra repository `2.3.4` is still the newest version.

**Comment by persapiens** [comment]
I agree @larsgrefer . `2.3.3.99` has been just released.

I got runtime error with `2.3.4` submitting button. Tests did not capture it :( This error did not occur with `2.3.3.99`. That's why I changed.

**Comment by persapiens** [comment]
@larsgrefer, do I release joinfaces `3.2.0` with mojarra `2.3.3.99` today or wait until fixing `2.4.0` issue described above?

**Comment by persapiens** [comment]
We could stay with mojarra `2.3.3` too...

**Comment by larsgrefer** [comment]
According to the commit history of the mojarra git repository, 2.3.3.99 is actually the former 2.4.0-SNAPSHOT.

Let me have a look at the error.

**Comment by larsgrefer** [comment]
@persapiens What error did you get?

**Comment by persapiens** [comment]
- build joinfaces master branch
- build [joinfaces-maven-jar-example mojarra-2.3.4 branch](https://github.com/persapiens/joinfaces-maven-jar-example/tree/mojarra-2.3.4)
- run `java -jar target/target/joinfaces-example-3.1.1-SNAPSHOT.jar`
- go to http://localhost:8080/welcomeConverter.jsf
- fill anything e press Submit
- you will get error:
```
2018-04-13 19:58:12.396 ERROR 9524 --- [io-8080-exec-10] j.e.resource.webcontainer.jsf.context    : java.lang.IllegalArgumentException: Unrecognized Content Type.
	at com.sun.faces.renderkit.RenderKitImpl.createResponseWriter(RenderKitImpl.java:283)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.createResponseWriter(FaceletViewHandlingStrategy.java:1160)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:438)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:194)
	at org.ocpsoft.rewrite.faces.RewriteViewHandler.renderView(RewriteViewHandler.java:196)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:126)
```

**Comment by persapiens** [comment]
@larsgrefer could you reproduce the error?

**Comment by larsgrefer** [comment]
But we can fix it at our side. I will open a PR for the maven-jar-example.

**Comment by larsgrefer** [comment]
@persapiens With joinfaces/joinfaces-maven-jar-example#158 and joinfaces/joinfaces-maven-war-example#54 we can go with Mojarra 2.3.4

**Comment by persapiens** [comment]
You are unbelievable @larsgrefer .

Thank you very much again.

**Pull request merged**
