### PR TITLE
Using assertThatExceptionOfType instead of assertThrows

### PR DESCRIPTION
**Pull request by persapiens**
Using assertThatExceptionOfType instead of assertThrows to [avoid spotbugs false positive with Assertions.assertThrows](https://github.com/spotbugs/spotbugs/issues/2628).

It is a tentative fix to improve the code readability as discussed in #1953.

### CODE REVIEW

**Review by larsgrefer — CHANGES_REQUESTED** [review]
This looks way better than the otherwise pointless isNotNull() check.

But could you fix the line endings here? Your PR changes the whole file from LF to CRLF

**Comment by persapiens** [comment]
> This looks way better than the otherwise pointless isNotNull() check.
> 
> But could you fix the line endings here? Your PR changes the whole file from LF to CRLF

Sure. @larsgrefer I edited with Windows, and the ide defaults to CRLF. I changed the ide default to LF.

**Review by larsgrefer — APPROVED** [review]

**Comment by larsgrefer** [comment]
Looks good to me now.

You can either configure your editor/IDE to LF or configure git to convert it on the fly with the `core.autocrlf` config option

**Comment by persapiens** [comment]
> Looks good to me now.
> 
> You can either configure your editor/IDE to LF or configure git to convert it on the fly with the `core.autocrlf` config option

`core.autocrlf` config option is new to me. Thanks.

**Pull request merged**
