### PR TITLE
Spring Boot 2.1 and Java 11

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by persapiens** [comment]
It will be a challenging task.

[This](https://medium.com/criciumadev/its-time-migrating-to-java-11-5eb3868354f9) is a great article about running Spring Boot 2.0.x app at Java 11. There are many libraries and plugins updates and others tricks.

More, it seems [Spring Boot 2.1.x will fully support Java 11](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9-and-above). I'm not sure, but Spring Boot 2.1.x can force JoinFaces 4.x creation.

**Comment by larsgrefer** [comment]
@persapiens Which version number should we use for the Joinfaces release building on Spring Boot 2.1 and Java 11? Just 3.3 or should we jump to 4.0?

**Comment by persapiens** [comment]
JoinFaces code has almost no changes, however we modified our System Requirements a lot:
- Java 11: added this functionality in backward-compatible manner to Java 8 and Java 10.
- Spring Boot 2.1: **is this functionality backward-compatible with Spring Boot 2.0**?

**Comment by persapiens** [comment]
So l vote `3.3` because of Spring Boot 2.1 functionality added in a backwards-compatible too.

What do you think about creating joinfaces 3.2 branch and merging this PR after Spring Boot 2.1.0.RC1 ?

**Pull request merged**
