### PR TITLE
Fix file upload with Jetty and Primefaces.

### PR DESCRIPTION
**Pull request by nyilmaz**

### CODE REVIEW

**Comment by nyilmaz** [comment]
@persapiens I have checked examples are working against this code, could you also check?

**Comment by persapiens** [comment]
Hi @nyilmaz ,

    I could not check that it is working. I've tested this joinfaces branch snapshot with joinfaces-example (http://localhost:8080/index.jsf?content=fileUpload), but upload did not work. Could you verify this?

    I look forward your answer.

**Comment by nyilmaz** [comment]
@persapiens could you send me a not-working branch on joinfaces-example, so i'll test too. I still can work through file upload on jetty.

**Comment by persapiens** [comment]
@nyilmaz , I've just created [jsf-jetty-spring-boot-starter branch](https://github.com/joinfaces/joinfaces-example/tree/jsf-jetty-spring-boot-starter).

Could you test file upload at http://localhost:8080/index.jsf?content=fileUpload using this merge request.

Thanks for you attention.

**Comment by nyilmaz** [comment]
I'll add tests shortly @persapiens . This should work both native and commons file upload setting.

**Comment by persapiens** [comment]
@nyilmaz , I can confirm your pull request works.

However, I'll open one issue to discuss some aspects of this solution.

Thanks a lot again for your collaboration.

**Pull request merged**
