### PR TITLE
joinfaces dependencies

### PR DESCRIPTION
**Pull request by hammadirshad**
I extract join faces dependencies from join faces parent so the user can import join faces starters using dependency Management if they don't want to include join faces as a parent into the project.  

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.joinfaces</groupId>
                <artifactId>joinfaces-dependencies</artifactId>
                <version>3.0.0.RC2-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

This change also allows the user to change spring version by adding spring boot parent into the project.

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-parent</artifactId>
        <version>2.0.0.RC1</version>
        <relativePath/> 
    </parent>

### CODE REVIEW

**Comment by persapiens** [comment]
hi @hammadirshad ,

Today, it is already possible to use spring boot starter parent instead of the joinfaces parent. You can use spring boot starter and add joinfaces starter dependency. [See this for example.](https://github.com/ButterFaces/spring-boot-joinfaces/blob/master/pom.xml)

Is there any other motivation for this PR? Spring Boot project has parent and dependencies modules. Why they are useful?

I look forward your answer.

**Comment by hammadirshad** [comment]
Hi @persapiens, 
Thank you for the reply. the only problem with butterfaces example is
If have multiple maven modules then first I need to include all join faces starters (primefaces, butterfaces) with versions in my project parent  using dependencyManagement and then I will able to include these in my web module. 

    <dependencyManagement>
      <dependency>
            <groupId>org.joinfaces</groupId>
            <artifactId>butterfaces-spring-boot-starter</artifactId>
            <version>${joinfaces.version}</version>
        </dependency>
       <dependency>
            <groupId>org.joinfaces</groupId>
            <artifactId>primefaces-spring-boot-starter</artifactId>
            <version>${joinfaces.version}</version>
     </dependency>
    </dependencyManagement>

but with this PR I can add all starters in my project project parent.

    <dependencyManagement>
     <dependencies>
        <dependency>
            <groupId>org.joinfaces</groupId>
            <artifactId>joinfaces-dependencies</artifactId>
            <version>${joinfaces.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
     </dependencies>
    </dependencyManagement>

**Comment by hammadirshad** [comment]
Just for refrence 
start.spring.io use same pom import method to import spring-boot-admin starters  into project.

**Comment by persapiens** [comment]
I think I got the idea. 

Let's merge it. Anyway, joinfaces-dependencies will inherit instead of import spring-boot-dependencies. 

According to the Spring Boot docs, `when using Spring Boot without the parent POM, you can still keep the benefit of the dependency management (but not the plugin management).`

Thanks a lot.

**Pull request merged**
