### PR TITLE
[WIP] Spring Boot 2.0.0.M4

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by persapiens** [comment]
It is time to create the 2.x branch before merging this, isn't it?

**Comment by persapiens** [comment]
You created 2.x branch!

**Comment by larsgrefer** [comment]
@persapiens Can you have a look at the failing tests?

**Comment by persapiens** [comment]
@larsgrefer I've just reviewed your PR.

**Comment by persapiens** [comment]
Is it ok to merge into master @larsgrefer ?

**Pull request merged**
