### PR TITLE
Support for JSF 2.3

### LINKED ISSUE #268: Support for JSF 2.3
With JSF 2.3 now released, the JSF game is now really on!

http://arjan-tijms.omnifaces.org/2017/03/jsf-23-released.html

Any plans to support JSF 2.3?

### PR DESCRIPTION
**Pull request by deki**
updated dependencies, fixes #268

### CODE REVIEW

**Comment by larmic** [comment]
Hi Dennis,

are you sure all JSF Frameworks (PrimeFaces, ...) still works with JSF 2.3?

**Comment by deki** [comment]
Well I've not tested everything, but I'm not aware of any issues or incompatible changes.

**Comment by persapiens** [comment]
I think this task could not be a trivial one. I see two obstacles: 

- compatibilities with other JSF libraries (PrimeFaces, ButterFaces, BootsFaces): we could just wait a little 
 or help them.

- the **required full** CDI implementation of JSF 2.3: this is challenging. I've discussed about it [here](#187). Have you ever tried running JSF 2.3 without a full CDI implementation? What do you think about?

**Comment by deki** [comment]
Usually I add OpenWebBeans without actually using CDI stuff. In my view it doesn't make sense to mix up CDI and Spring annotations.

**Comment by persapiens** [comment]
Before jsf 2.3, we have one "container of beans" to work with spring boot: Spring.

With jsf 2.3 and later, we have "two containers of beans" to work with spring boot: Spring and cdi implementation (OpenWebBeans or Weld). Application will become bigger. More, if you want to enable communication between beans of these two containers (very common use case), you will have two options: - create a bridge between these two containers or - make/help spring implementing full CDI (here, you will have only one container of beans again).

**Comment by larmic** [comment]
ButterFaces seems to work with JSF 2.3. We will release version 3.0.0 after JEE8 is out.

**Comment by persapiens** [comment]
hi @deki ,

I realized that it is still possible to run JSF 2.3 without full CDI implementation. So, there is no issue to upgrade JoinFaces to use JSF 2.3.

However, JoinFaces changed a bit and this PR now conflicts. So, I send another PR #366 to upgrade JSF to 2.3 and autoconfigure new mojarra 2.3.3 properties.

Anyway, thanks a lot for your contribution.

**Comment by deki** [comment]
OK I'll close this one.

**Pull request closed without merging**
