### PR TITLE
Improve Properties

### PR DESCRIPTION
**Pull request by larsgrefer**
- Reflection based system for setting init parameters
  - The property fields are annotated with `@ServletContextInitParameter`
  - Only one `ServletContextConfigurer` which uses Reflection to read the Annotations in the Properties object
  - `PropertiesCustomizer<>` mechanism to set properties in code
  - One base-class for all properties related `*AutoConfiguration`-classes which does all the work
- different `*Properties`-classes per Version
  - for Primefaces 5.0, 5.1, 5.2 and 6.0
  - for JSF 2.0, 2.1, 2.2
  - own `@ConditionalOnClassVersion` annotation

### CODE REVIEW

**Comment by larsgrefer** [comment]
What can we do about the line coverage of `org.joinfaces.configuration.ReflectiveServletContextConfigurer`? 8% are missing because of the catch clauses.

**Comment by larsgrefer** [comment]
@persapiens What's your opinion on this?

**Comment by larsgrefer** [comment]
I think forcing 100% line coverage for the `*Properties` is a bit too much. They are just POJO's

**Comment by larsgrefer** [comment]
@persapiens Why is the coverage check for `org.joinfaces.javaxfaces.JavaxFaces2_2Properties` failing?

**Comment by persapiens** [comment]
I didn't find the missing check, but it is unimportant.

Thanks again @larsgrefer

**Pull request merged**
