### PR TITLE
Allow JSF 2.3-like injection of JSF artifacts

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by persapiens** [comment]
hi @larsgrefer, is this PR useful after #366?

I look forward your answer.

**Comment by larsgrefer** [comment]
@persapiens 
TL;DR: Yes, it's still useful. The new injections in JSF 2.3 only work with CDI.

The new injections in JSF 2.3 are implemented as CDI providers. This PR translates these providers to Spring bean definitions.

**Comment by persapiens** [comment]
Well, joinfaces should solve JSF and Spring Boot integration, but we are solving CDI and Spring Boot integration here.

Anyway, I tried to understand why build failed. I could do some steps:

1. Class org.joinfaces.javaxfacesJsfBeansAutoConfigurationIT. Change line 64:

```java
String html = this.testRestTemplate.getForObject("/faces/jsfBeansTest.xhtml", String.class);
```
to 
```java
String html = this.testRestTemplate.getForObject("/faces/jsfBeansTest.jsf", String.class);
```

2. pom.xml. Add
```xml
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>jstl</artifactId>
            <scope>test</scope>
        </dependency>
```

Now, I get the error:

> java.lang.IllegalStateException: Cannot create a session after the response has been committed

**Comment by persapiens** [comment]
hi @larsgrefer ,

Will you include tests of this new feature? I could simple one like checking the presence of JSF artifacts in spring context.

**Comment by larsgrefer** [comment]
@persapiens Only checking their presence will not generate the needed coverage

**Comment by larsgrefer** [comment]
@persapiens I've added some tests to increase the coverage a bit, but in my opinion those tests are pretty useless since the test code is more complex than the code under test.

**Comment by persapiens** [comment]
Anyway, I think checking the presence of JSF artifacts in spring context is simple and ensure the implemented feature. We could decrease coverage limits too. I want to merge this PR before realising 3.0.0.

**Pull request merged**
