### PR TITLE
Update Mojarra to 2.3.5

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by persapiens** [comment]
@larsgrefer do you know why we have so many mojarra versions: 3.3.3.102, 3.3.5, 3.4.0? Which one is the latest stable release?

I look forward to your answer.

**Comment by larsgrefer** [comment]
Unfortunately these versions aren't documented anywhere.

The `2.3.3.99` release seems to have something todo with the migration to the Eclipse Foundation as part of the EE4J/JakartaEE project

**Comment by persapiens** [comment]
I've just opened this [issue](https://github.com/eclipse-ee4j/mojarra/issues/4390) to help us.

**Comment by persapiens** [comment]
After @arjantijms response, which one should we use by mojarra default: 3.3.3.102 or 3.3.5?

**Comment by larsgrefer** [comment]
AFAIK both `3.3.3.102` and `3.3.5` are equally correct and wrong at the same time.

**Comment by arjantijms** [comment]
>AFAIK both 3.3.3.102 and 3.3.5 are equally correct and wrong at the same time.

That's true, with the note that it's 2.3.3.102 and 2.3.5 ;) It's essentially both 2.3.3, but due to some miscommunications and mistakes in the procedures, we ended up with two separate branches.

If you're being hit by any of the bugs fixed in 2.3.5, then obvious 2.3.5 is the version to use, otherwise 2.3.3.102 may be better as this is the version that has been donated to Eclipse and from which all previous versions will be made.

2.3.5 is basically a dead branch. Oracle may decide to continue it (under Oracle's copyright/IP) but we haven't heard much about that.

But indeed they are equally correct and wrong at the same time.

**Comment by persapiens** [comment]
So, I think we could switch to `2.3.3.102`. If our users report any serious issues that `2.3.5` solves, we switch again.

Meanwhile, we wait for next Eclipse version.

**Pull request merged**
