### PR TITLE
configure AdminFaces using Spring Boot application.yml or application.properties

### PR DESCRIPTION
**Pull request by persapiens**

### CODE REVIEW

**Comment by larsgrefer** [comment]
Have you tried something like this?
```java
@Bean
@ConfigurationProperties("jsf.adminfaces")
public AdminConfig adminConfig() {
    return new AdminConfig();
}
```

**Comment by persapiens** [comment]
Did you mean testing `AdminConfigWrapper` creation? I've just included it.

`AdminConfig` is already created because of `@ApplicationScoped and @Named` annotations.
The solution replaces `AdminConfig` to `AdminConfigWrapper`. `AdminConfigWrapper` overrides `loadDefaults` method, loading `AdminFacesProperties` and configuring `AdminConfig` attributes properly.

**Comment by larsgrefer** [comment]
My Idea was to override/replace the `BeanDefintion` found by scanning the class with an explicit one which is directly annotated with `@ComponentScan`. I'm currently testing if this would work as expected

**Comment by larsgrefer** [comment]
Just replacing the `AdminConfig` bean doesn't work, because the nested property `controlSidebar` property isn't properly mapped.

**Pull request merged**
