### PR TITLE
Use classgraph instead of reflections

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by larsgrefer** [comment]
I've tried to implement a general solution for all `ServletContainerInitializer`s, so filtering for `META-INF/faces-config.xml` files isn't an option there, but I'll have a look if I can further improve the performance.

**Comment by larsgrefer** [comment]
On my machine (MacBook Air 2014, 1.4GHz i5, 4GB RAM) the complete scan takes between 2.5 and 11 seconds.

2.5 to 3 seconds for the `test-projects/mojarra-tomcat` module which has a minimal classpath.

8 to 11 seconds for the `joinfaces-autoconfigure` module which has a very big test-classpath (all servlet containers, both JSF implementations, and all component libraries)

**Comment by persapiens** [comment]
I used AMD 3 cores, 0.8GHz, 8GB RAM. Using joinfaces-maven-jar-example, Reflections took around 0.750s while ClassGraph took 4.5s. It is a big difference. It happens because current Reflections usage scans only JSF related jars while ClassGraph scans all jars (7 x 84 in this case).

Is it possible to scan only JSF related urls (component libraries, mojarra, myfaces, classes folder) with ClassGraph?

**Comment by larsgrefer** [comment]
These are the Packages where we are finding classes from:

```
com.sun.faces.cdi
com.sun.faces.component
com.sun.faces.ext.component
com.sun.faces.ext.render
com.sun.faces.ext.validator
com.sun.faces.facelets.compiler
com.sun.faces.facelets.component
com.sun.faces.facelets.tag.composite
com.sun.faces.facelets.tag.jsf
com.sun.faces.facelets.tag.ui
com.sun.faces.lifecycle
com.sun.faces.push
com.sun.faces.renderkit.html_basic
com.sun.faces.scripting.groovy
com.sun.faces.taglib.jsf_core
de.beyondjava.angularFaces.components.puiDiv
de.beyondjava.angularFaces.components.puiLabel
de.beyondjava.angularFaces.components.puiMessage
de.beyondjava.angularFaces.components.puiModelSync
de.beyondjava.angularFaces.components.puiSpan
de.beyondjava.angularFaces.components.puiSync
de.beyondjava.angularFaces.components.puiupdateModelAfterAJAXRequest
de.beyondjava.angularFaces.core.i18n
javax.faces.component
javax.faces.component.html
javax.faces.convert
javax.faces.render
javax.faces.validator
net.bootsfaces.component
net.bootsfaces.component.accordion
net.bootsfaces.component.ajax
net.bootsfaces.component.alert
net.bootsfaces.component.badge
net.bootsfaces.component.breadcrumbs
net.bootsfaces.component.button
net.bootsfaces.component.buttonGroup
net.bootsfaces.component.buttonToolbar
net.bootsfaces.component.canvas
net.bootsfaces.component.carousel
net.bootsfaces.component.carouselCaption
net.bootsfaces.component.carouselControl
net.bootsfaces.component.carouselItem
net.bootsfaces.component.colorPicker
net.bootsfaces.component.column
net.bootsfaces.component.commandButton
net.bootsfaces.component.commandLink
net.bootsfaces.component.container
net.bootsfaces.component.dataTable
net.bootsfaces.component.dataTableColumn
net.bootsfaces.component.dateTimePicker
net.bootsfaces.component.datepicker
net.bootsfaces.component.defaultCommand
net.bootsfaces.component.dropButton
net.bootsfaces.component.dropMenu
net.bootsfaces.component.fetchBeanInfos
net.bootsfaces.component.flyOutMenu
net.bootsfaces.component.focus
net.bootsfaces.component.form
net.bootsfaces.component.formGroup
net.bootsfaces.component.fullCalendar
net.bootsfaces.component.growl
net.bootsfaces.component.gyroscope
net.bootsfaces.component.icon
net.bootsfaces.component.iconAwesome
net.bootsfaces.component.image
net.bootsfaces.component.inputSecret
net.bootsfaces.component.inputText
net.bootsfaces.component.inputTextarea
net.bootsfaces.component.internalCssScriptResource
net.bootsfaces.component.internalJavaScriptResource
net.bootsfaces.component.jumbotron
net.bootsfaces.component.kebab
net.bootsfaces.component.label
net.bootsfaces.component.link
net.bootsfaces.component.linksContainer
net.bootsfaces.component.listLinks
net.bootsfaces.component.message
net.bootsfaces.component.messages
net.bootsfaces.component.modal
net.bootsfaces.component.navBar
net.bootsfaces.component.navBarLinks
net.bootsfaces.component.navCommandLink
net.bootsfaces.component.navLink
net.bootsfaces.component.openStreetMap
net.bootsfaces.component.panel
net.bootsfaces.component.panelGrid
net.bootsfaces.component.pillLinks
net.bootsfaces.component.poll
net.bootsfaces.component.progressBar
net.bootsfaces.component.radiobutton
net.bootsfaces.component.remoteCommand
net.bootsfaces.component.row
net.bootsfaces.component.scrollSpy
net.bootsfaces.component.scrollUp
net.bootsfaces.component.selectBooleanCheckbox
net.bootsfaces.component.selectMultiMenu
net.bootsfaces.component.selectOneMenu
net.bootsfaces.component.shake
net.bootsfaces.component.slider
net.bootsfaces.component.slider2
net.bootsfaces.component.socialShare
net.bootsfaces.component.spinner
net.bootsfaces.component.switchComponent
net.bootsfaces.component.tab
net.bootsfaces.component.tabLinks
net.bootsfaces.component.tabView
net.bootsfaces.component.thumbnail
net.bootsfaces.component.touchSpin
net.bootsfaces.component.tree
net.bootsfaces.component.video
net.bootsfaces.component.well
net.bootsfaces.expressions
net.bootsfaces.listeners
net.bootsfaces.render
org.ajax4jsf.component
org.ajax4jsf.renderkit
org.apache.myfaces.cdi.converter
org.apache.myfaces.cdi.validator
org.apache.myfaces.component
org.apache.myfaces.component.validate
org.apache.myfaces.el
org.apache.myfaces.push
org.apache.myfaces.renderkit.html
org.apache.myfaces.shared.renderkit.html
org.apache.myfaces.taglib.core
org.apache.myfaces.view.facelets.component
org.apache.myfaces.view.facelets.el
org.apache.myfaces.view.facelets.tag.composite
org.apache.myfaces.view.facelets.tag.jsf
org.apache.myfaces.view.facelets.tag.ui
org.apache.tomcat.websocket.pojo
org.butterfaces.component.base.component
org.butterfaces.component.base.renderer
org.butterfaces.component.html
org.butterfaces.component.html.action
org.butterfaces.component.html.ajax
org.butterfaces.component.html.message
org.butterfaces.component.html.repeat
org.butterfaces.component.html.resourcelibraries
org.butterfaces.component.html.table
org.butterfaces.component.html.text
org.butterfaces.component.html.text.part
org.butterfaces.component.html.tree
org.butterfaces.component.renderkit.html_basic
org.butterfaces.component.renderkit.html_basic.action
org.butterfaces.component.renderkit.html_basic.ajax
org.butterfaces.component.renderkit.html_basic.repeat
org.butterfaces.component.renderkit.html_basic.resourcelibraries
org.butterfaces.component.renderkit.html_basic.table
org.butterfaces.component.renderkit.html_basic.text
org.butterfaces.component.renderkit.html_basic.text.part
org.icefaces.ace.component.accordion
org.icefaces.ace.component.ajax
org.icefaces.ace.component.animation
org.icefaces.ace.component.audioplayer
org.icefaces.ace.component.autocompleteentry
org.icefaces.ace.component.borderlayout
org.icefaces.ace.component.breadcrumbmenu
org.icefaces.ace.component.buttongroup
org.icefaces.ace.component.celleditor
org.icefaces.ace.component.chart
org.icefaces.ace.component.checkboxbutton
org.icefaces.ace.component.checkboxbuttons
org.icefaces.ace.component.clientValidator
org.icefaces.ace.component.colorentry
org.icefaces.ace.component.column
org.icefaces.ace.component.columngroup
org.icefaces.ace.component.combobox
org.icefaces.ace.component.confirmationdialog
org.icefaces.ace.component.contextmenu
org.icefaces.ace.component.dashboard
org.icefaces.ace.component.dataexporter
org.icefaces.ace.component.datatable
org.icefaces.ace.component.datetimeentry
org.icefaces.ace.component.delegate
org.icefaces.ace.component.dialog
org.icefaces.ace.component.dnd
org.icefaces.ace.component.drawerpanel
org.icefaces.ace.component.dynamicresource
org.icefaces.ace.component.excludefromexport
org.icefaces.ace.component.expansiontoggler
org.icefaces.ace.component.fileentry
org.icefaces.ace.component.gmap
org.icefaces.ace.component.graphicimage
org.icefaces.ace.component.growlmessages
org.icefaces.ace.component.linkbutton
org.icefaces.ace.component.list
org.icefaces.ace.component.listcontrol
org.icefaces.ace.component.listexporter
org.icefaces.ace.component.listexportervalue
org.icefaces.ace.component.maskedentry
org.icefaces.ace.component.menu
org.icefaces.ace.component.menubar
org.icefaces.ace.component.menubutton
org.icefaces.ace.component.menucolumn
org.icefaces.ace.component.menuitem
org.icefaces.ace.component.menuseparator
org.icefaces.ace.component.message
org.icefaces.ace.component.messages
org.icefaces.ace.component.multicolumnsubmenu
org.icefaces.ace.component.node
org.icefaces.ace.component.notificationpanel
org.icefaces.ace.component.panel
org.icefaces.ace.component.panelexpansion
org.icefaces.ace.component.panelstack
org.icefaces.ace.component.printer
org.icefaces.ace.component.progressbar
org.icefaces.ace.component.pushbutton
org.icefaces.ace.component.qrcode
org.icefaces.ace.component.radiobutton
org.icefaces.ace.component.radiobuttons
org.icefaces.ace.component.resizable
org.icefaces.ace.component.richtextentry
org.icefaces.ace.component.row
org.icefaces.ace.component.roweditor
org.icefaces.ace.component.rowexpansion
org.icefaces.ace.component.schedule
org.icefaces.ace.component.scheduleexporter
org.icefaces.ace.component.selectmenu
org.icefaces.ace.component.simpleselectonemenu
org.icefaces.ace.component.sliderentry
org.icefaces.ace.component.splitpane
org.icefaces.ace.component.stackpane
org.icefaces.ace.component.submenu
org.icefaces.ace.component.submitmonitor
org.icefaces.ace.component.tableconfigpanel
org.icefaces.ace.component.tabset
org.icefaces.ace.component.textareaentry
org.icefaces.ace.component.textentry
org.icefaces.ace.component.theme
org.icefaces.ace.component.themeselect
org.icefaces.ace.component.tooltip
org.icefaces.ace.component.tree
org.icefaces.ace.component.tristatecheckbox
org.icefaces.ace.component.videoplayer
org.icefaces.ace.renderkit
org.icefaces.impl.application
org.icefaces.impl.component
org.icefaces.impl.event
org.icefaces.impl.facelets.tag.icefaces.core
org.icefaces.impl.push.servlet
org.icefaces.impl.renderkit
org.icefaces.impl.renderkit.html_basic
org.omnifaces.component.input
org.omnifaces.component.input.componentidparam
org.omnifaces.component.messages
org.omnifaces.component.output
org.omnifaces.component.script
org.omnifaces.component.tree
org.omnifaces.component.validator
org.omnifaces.converter
org.omnifaces.event
org.omnifaces.eventlistener
org.omnifaces.renderer
org.omnifaces.taghandler
org.omnifaces.validator
org.primefaces.application.resource
org.primefaces.behavior.ajax
org.primefaces.behavior.printer
org.primefaces.component.accordionpanel
org.primefaces.component.ajaxexceptionhandler
org.primefaces.component.ajaxstatus
org.primefaces.component.api
org.primefaces.component.autocomplete
org.primefaces.component.autoupdate
org.primefaces.component.barcode
org.primefaces.component.blockui
org.primefaces.component.breadcrumb
org.primefaces.component.button
org.primefaces.component.cache
org.primefaces.component.calendar
org.primefaces.component.captcha
org.primefaces.component.carousel
org.primefaces.component.celleditor
org.primefaces.component.chart
org.primefaces.component.checkbox
org.primefaces.component.chips
org.primefaces.component.clock
org.primefaces.component.colorpicker
org.primefaces.component.column
org.primefaces.component.column.renderer
org.primefaces.component.columngroup
org.primefaces.component.columns
org.primefaces.component.columntoggler
org.primefaces.component.commandbutton
org.primefaces.component.commandlink
org.primefaces.component.confirmdialog
org.primefaces.component.contentflow
org.primefaces.component.contextmenu
org.primefaces.component.dashboard
org.primefaces.component.datagrid
org.primefaces.component.datalist
org.primefaces.component.datascroller
org.primefaces.component.datatable
org.primefaces.component.defaultcommand
org.primefaces.component.diagram
org.primefaces.component.dialog
org.primefaces.component.dnd
org.primefaces.component.dock
org.primefaces.component.editor
org.primefaces.component.effect
org.primefaces.component.feedreader
org.primefaces.component.fieldset
org.primefaces.component.fileupload
org.primefaces.component.focus
org.primefaces.component.fragment
org.primefaces.component.galleria
org.primefaces.component.gmap
org.primefaces.component.graphicimage
org.primefaces.component.growl
org.primefaces.component.headerrow
org.primefaces.component.hotkey
org.primefaces.component.idlemonitor
org.primefaces.component.imagecompare
org.primefaces.component.imagecropper
org.primefaces.component.imageswitch
org.primefaces.component.inplace
org.primefaces.component.inputmask
org.primefaces.component.inputnumber
org.primefaces.component.inputswitch
org.primefaces.component.inputtext
org.primefaces.component.inputtextarea
org.primefaces.component.keyboard
org.primefaces.component.keyfilter
org.primefaces.component.knob
org.primefaces.component.layout
org.primefaces.component.lifecycle
org.primefaces.component.lightbox
org.primefaces.component.link
org.primefaces.component.log
org.primefaces.component.media
org.primefaces.component.megamenu
org.primefaces.component.menu
org.primefaces.component.menubar
org.primefaces.component.menubutton
org.primefaces.component.menuitem
org.primefaces.component.message
org.primefaces.component.messages
org.primefaces.component.mindmap
org.primefaces.component.multiselectlistbox
org.primefaces.component.notificationbar
org.primefaces.component.orderlist
org.primefaces.component.organigram
org.primefaces.component.organigramnode
org.primefaces.component.outputlabel
org.primefaces.component.outputpanel
org.primefaces.component.overlaypanel
org.primefaces.component.panel
org.primefaces.component.panelgrid
org.primefaces.component.panelmenu
org.primefaces.component.password
org.primefaces.component.photocam
org.primefaces.component.picklist
org.primefaces.component.poll
org.primefaces.component.progressbar
org.primefaces.component.radiobutton
org.primefaces.component.rating
org.primefaces.component.remotecommand
org.primefaces.component.repeat
org.primefaces.component.resizable
org.primefaces.component.ribbon
org.primefaces.component.ring
org.primefaces.component.row
org.primefaces.component.row.renderer
org.primefaces.component.roweditor
org.primefaces.component.rowexpansion
org.primefaces.component.rowtoggler
org.primefaces.component.schedule
org.primefaces.component.scrollpanel
org.primefaces.component.selectbooleanbutton
org.primefaces.component.selectbooleancheckbox
org.primefaces.component.selectcheckboxmenu
org.primefaces.component.selectmanybutton
org.primefaces.component.selectmanycheckbox
org.primefaces.component.selectmanymenu
org.primefaces.component.selectonebutton
org.primefaces.component.selectonelistbox
org.primefaces.component.selectonemenu
org.primefaces.component.selectoneradio
org.primefaces.component.separator
org.primefaces.component.sidebar
org.primefaces.component.signature
org.primefaces.component.slidemenu
org.primefaces.component.slider
org.primefaces.component.socket
org.primefaces.component.spacer
org.primefaces.component.spinner
org.primefaces.component.splitbutton
org.primefaces.component.spotlight
org.primefaces.component.stack
org.primefaces.component.steps
org.primefaces.component.sticky
org.primefaces.component.submenu
org.primefaces.component.subtable
org.primefaces.component.summaryrow
org.primefaces.component.tabmenu
org.primefaces.component.tabview
org.primefaces.component.tagcloud
org.primefaces.component.terminal
org.primefaces.component.texteditor
org.primefaces.component.themeswitcher
org.primefaces.component.tieredmenu
org.primefaces.component.timeline
org.primefaces.component.toolbar
org.primefaces.component.tooltip
org.primefaces.component.tree
org.primefaces.component.treetable
org.primefaces.component.tristatecheckbox
org.primefaces.component.watermark
org.primefaces.component.wizard
org.primefaces.convert
org.primefaces.mobile.component.content
org.primefaces.mobile.component.field
org.primefaces.mobile.component.footer
org.primefaces.mobile.component.header
org.primefaces.mobile.component.inputslider
org.primefaces.mobile.component.page
org.primefaces.mobile.component.rangeslider
org.primefaces.mobile.component.uiswitch
org.primefaces.mobile.renderkit
org.primefaces.mobile.renderkit.paginator
org.primefaces.renderkit
org.primefaces.util
org.primefaces.validate
org.richfaces.component
org.richfaces.component.html
org.richfaces.convert
org.richfaces.renderkit
org.richfaces.renderkit.html
org.richfaces.ui.output.component
org.richfaces.validator
org.springframework.web.jsf
```

**Comment by lukehutch** [comment]
In ClassGraph Master, you can filter for jars containing specified resource paths, e.g. `"META-INF/faces-config.xml"`:

* `whitelistClasspathElementsContainingResourcePath(String... paths)`
* `blacklistClasspathElementsContainingResourcePath(String... paths)`

(I'm not sure if that is still relevant given the earlier comment in this thread about `ServletContainerInitializer` though.)

Note that you can always set up build-time scanning to generate the list of jars containing given resource paths, e.g.  `"META-INF/faces-config.xml"`, and then save the names of the jars in a resource file that can later be passed into `.whitelistJars()` (in case the classpath changes at runtime).

https://github.com/classgraph/classgraph/wiki/Build-Time-Scanning

**Comment by larsgrefer** [comment]
We basically have to implement Section 8.2.4 of the _Servlet Specification_ here for all Joinfaces-based applications which use an embedded servlet-container.

I think build time scanning would be an option for users concerned about startup time.

**Comment by persapiens** [comment]
The latest implementation improved performance: it took 1s. However, it is still slower than old implementation (0.33s) at AMD 3,4GHz Octa Core 16GB RAM using joinfaces-maven-jar-example. 
I think both build time and startup time are important.
I did not understand why filtering jars with `JSF marks` like _META-INF/faces-config.xml_ is not an option.  This would reduce more than 90% ClassGraph scan scope. That's why old implementation is faster. Why not having an specific JSF solution for `ServletContainerInitializer`?

**Comment by larsgrefer** [comment]
There could be a significant performance improvement when classgraph/classgraph#281 and spring-projects/spring-boot#15096 are resolved

**Comment by persapiens** [comment]
@larsgrefer I've merged [Gradle PR](https://github.com/joinfaces/joinfaces/pull/539). Could you verify and push my commits to avoid conflicting here?

**Comment by larsgrefer** [comment]
> I did not understand why filtering jars with JSF marks like META-INF/faces-config.xml is not an option.

Because there are classes which are matched by the `@HandlesTypes` annotation of either mojarra or myfaces, that don't have a `META-INF/faces-config.xml` in the same classpath root. For example `org.springframework.web.jsf.DelegatingPhaseListenerMulticaster`

**Comment by persapiens** [comment]
thanks a lot @lukehutch

**Comment by lukehutch** [comment]
@larsgrefer @persapiens you're welcome... so build-time scanning worked out OK?

**Comment by larsgrefer** [comment]
> @larsgrefer @persapiens you're welcome... so build-time scanning worked out OK?

It was a bit tricky to set up, but we're confident it should work now.

**Comment by lukehutch** [comment]
@larsgrefer I wrote a custom zipfile central directory parser for ClassGraph, so that nested jarfiles that are stored (rather than deflated) can have their central directory read without having to extract the inner jarfile to a temporary file. For a typical Spring Boot jarfile, I saw an 80x speedup to read all entries of all nested jars (without actually reading the contents of any of the entries). If you are reading the contents of lots of classfiles, the speedup will be much lower than this, since the bottleneck will then be the reading, deflating and scanning of classfiles, but the speedup should still be appreciable for a large classpath consisting of lots of nested jars.

This is a big change, so I would really appreciate it if you could please (1) report before-and-after benchmark numbers, comparing the latest released version to the below commit, and (2) compare the scan output before and after this change, to make sure there are no behavioral changes (the scan results should be identical, although the verbose logs will be a bit different).

Please clone the version at this commit: 
https://github.com/classgraph/classgraph/commit/c7c431ce6ccaaa35dc093702d6e0d5b9bf5b01f6

All going well, this will be released in version 4.6.0 of ClassGraph. Thanks!

**Comment by lukehutch** [comment]
@larsgrefer I just released version 4.6.0 of ClassGraph with these changes. 

I saw somewhere in your PR that you were using a method in ClassGraph's `JarUtils` class to determine if a given jar was in the JRE's lib or ext directory. This is a non-API class, and in ClassGraph 4.6.0 non-API classes were moved to a new "nonapi" package, which is not exported in the module descriptor.

This call shouldn't be needed now though, because in the new version of ClassGraph, enabling scanning of `rt.jar` and lib/ext dirs has been separated:

https://github.com/classgraph/classgraph/releases/tag/classgraph-4.6.0

Let me know if there's anything you have trouble getting anything working with this new version. Thanks for all your input and pull requests, they really helped improve this release, and inspired some major performance improvements.

**Pull request merged**
